blog/urls.py
from django.urls import path
from .views import BlogListView



app_name="blog"

urlpatterns = [
    path('',BlogListView.as_view(), name="home")
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(),name="home"),
    path('blog/',include('blog.urls',namespace='blog'))#el as_view hace referencia a qie estamos trabajando con una clase
    
]

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.views.generic import View #utilizamos vistas de clases la View lo importamos

# Create your views here.
class BlogListView(View):
    def get(self, request, *args, **kwargs):
        context={
            
        }
        return render(request, 'blog_list.html',context)

core/views.py
from django.views.generic import View #utilizamos vistas de clases la View lo importamos
from django.shortcuts import render #importamos el render

class HomeView(View):#cuando utilizamos una clase debemos utilizar self
    def get(self, request, *args, **kwars):#esto hace referencia a cualquier parametro que nuestro request pueda tener lo vamos a utilizar para obetr el id del ussuario
        context={
            
        }
        return render(request, 'index.html',context)#aqui retornamos el template lo que tiene el osea index.html osea la informacion en html q vamos a mostrar el template gusrda todos los html

templates/index.html
<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <a href="{%url 'blog:home'%}">mi blog</a>
        
        
    </body>
</html>